name: Deploy Worker
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy page to cloudflare
    permissions:
      contents: read
      deployments: write
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build static site
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=thinhtv
